
Se ha generado el siguiente Error: Error en metodo LlenarCalls : Se produjo un error mientras se ejecutaba el comando. Vea la excepción interna para obtener detalles.

registrado el : 20/02/2019 12:57:58 con el usuario Administrador

=================================================================================================

Se ha generado el siguiente Error: Ocurrrio un error en ProcesarFicheros Se produjo un error mientras se ejecutaba el comando. Vea la excepción interna para obtener detalles.

registrado el : 20/02/2019 12:57:58 con el usuario Administrador

=================================================================================================

Se ha generado el siguiente Error: Error en metodo LlenarCalls : Se produjo un error mientras se ejecutaba el comando. Vea la excepción interna para obtener detalles.

registrado el : 20/02/2019 02:00:01 con el usuario Administrador

=================================================================================================
