
Se ha generado el siguiente Error: Error en metodo LlenarCalls : Se produjo un error mientras se ejecutaba el comando. Vea la excepción interna para obtener detalles.

registrado el : 07/02/2019 08:22:44 con el usuario Administrador

=================================================================================================

Se ha generado el siguiente Error: Ocurrrio un error en ProcesarFicheros Se produjo un error mientras se ejecutaba el comando. Vea la excepción interna para obtener detalles.

registrado el : 07/02/2019 08:22:44 con el usuario Administrador

=================================================================================================
